# pylint: disable=wildcard-import, method-hidden, missing-function-docstring, missing-module-docstring, protected-access
from mkdocs_dataview.query.solvers import ExpressionSolverService

tests = [
    ('1',            1),
    ('1 + 2',        3),
    ('1 + 2 - 3',    0),
    ('3 - 2 * 3',   -3),
    ('(3 - 2) * 3',  3),
    ('3 * (3 - 2)',  3),
    ('(3 * 3) - 2',  7),
    ('(3 * 3) * 2',  18),
    ('1 != 3',        True),
    ('2 != 2',        False),
    ('"a" != "b"',        True),
    ('"a" != "a"',        False),
    ('"a" != "A"',        True),
    ('3 >= 3',        True),
    ('3 >= 1',        True),
    ('3 >= -4',        True),
    ('3 >= 4',        False),
    ('3 > 3',        False),
    ('3 > 1',        True),
    ('3 > -4',        True),
    ('3 > 4',        False),
    ('3 <= 3',        True),
    ('3 <= 1',        False),
    ('3 <= -4',        False),
    ('3 <= 4',        True),
    ('3 < 3',        False),
    ('3 < 1',        False),
    ('3 < -4',        False),
    ('3 < 4',        True),
    ('NOT True',        False),
    ('NOT False',        True),
    ('NOT 1',        False),
    ('NOT 0',        True),
    ('true AND True',        True),
    ('3 < 4 AND True',        True),
    ('3 < 4 AND False',        False),
    ('4 < 4 AND True',        False),
    ('True AND 3 < 4 ',        True),
    ('False AND 3 < 4',        False),
    ('True AND 4 < 4',        False),
    ('True AND False OR True',        True),
    ('True OR False AND True',        True),
    ('False OR True AND False',        False),
    ('True AND False OR False',   False),
    ('False OR 0',        False),
    ('False OR 0 + 1',        True),
    ('3 * (3 - 2) == 3',        True),
    ('3 * (3 - 2) == (1 + 2)',  True),
    ('1 IN [1, 2, 3]',  True),
    ('0 IN [1, 2, 3]',  False),
    ('NOT 1 IN [1, 2, 3]',  False),
    ('NOT 0 IN [1, 2, 3]',  True),
    ('[1, 2, 3] CONTAINS 1',  True),
    ('[1, 2, 3] CONTAINS 0',  False),
    ('NOT [1, 2, 3] CONTAINS 1',  False),
    ('NOT [1, 2, 3] CONTAINS 0',  True),
    ('sum(1)',  1),
    ('sum(1, 2)',  3),
]

def test_parser_priority():
    for query, expected_result in tests:
        res = ExpressionSolverService(query).solve({})
        assert expected_result == res
